package dev.spanhol.day23;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Stack;

public class Day23 {
    String input = "mi-qh\n" +
            "ow-ys\n" +
            "qc-at\n" +
            "ou-bf\n" +
            "eb-id\n" +
            "gy-dc\n" +
            "dh-ja\n" +
            "li-ji\n" +
            "dc-ci\n" +
            "ni-xr\n" +
            "db-zg\n" +
            "ou-iq\n" +
            "qk-qx\n" +
            "kx-is\n" +
            "ek-ey\n" +
            "sj-uj\n" +
            "jv-ry\n" +
            "om-li\n" +
            "ri-ct\n" +
            "po-oq\n" +
            "nk-qs\n" +
            "av-eo\n" +
            "gb-or\n" +
            "vu-vw\n" +
            "ld-az\n" +
            "ex-oh\n" +
            "ci-ej\n" +
            "ag-mv\n" +
            "qu-xy\n" +
            "zg-rw\n" +
            "uv-rz\n" +
            "id-st\n" +
            "hg-in\n" +
            "wk-kb\n" +
            "ht-ab\n" +
            "zc-cv\n" +
            "gn-yy\n" +
            "jp-og\n" +
            "pz-to\n" +
            "gh-ud\n" +
            "zm-mv\n" +
            "gi-sq\n" +
            "ef-id\n" +
            "lt-zp\n" +
            "fu-ie\n" +
            "mi-nz\n" +
            "ck-tm\n" +
            "yu-fu\n" +
            "ge-tn\n" +
            "wp-vh\n" +
            "cb-uf\n" +
            "av-no\n" +
            "fu-ul\n" +
            "pk-hp\n" +
            "we-qc\n" +
            "ox-rz\n" +
            "li-my\n" +
            "gm-ut\n" +
            "yt-bn\n" +
            "fl-ri\n" +
            "ab-io\n" +
            "wg-ng\n" +
            "sg-cu\n" +
            "he-ll\n" +
            "vq-sq\n" +
            "ld-nh\n" +
            "jg-kx\n" +
            "tl-gj\n" +
            "yk-xf\n" +
            "ls-yt\n" +
            "ld-yg\n" +
            "tt-ot\n" +
            "wm-ob\n" +
            "pc-zz\n" +
            "jp-oc\n" +
            "pt-dr\n" +
            "nh-pc\n" +
            "yt-mx\n" +
            "kk-lm\n" +
            "ci-ti\n" +
            "ie-xa\n" +
            "dc-jv\n" +
            "rv-ep\n" +
            "jf-yn\n" +
            "yt-pd\n" +
            "mv-li\n" +
            "fu-ot\n" +
            "xg-dw\n" +
            "ed-ce\n" +
            "zz-yg\n" +
            "wq-ff\n" +
            "cm-oc\n" +
            "cu-qo\n" +
            "mt-vr\n" +
            "pw-vg\n" +
            "gh-xe\n" +
            "im-sx\n" +
            "ym-fs\n" +
            "ph-kr\n" +
            "qo-fu\n" +
            "zj-hb\n" +
            "em-rz\n" +
            "hu-qx\n" +
            "bg-qk\n" +
            "nn-pa\n" +
            "hj-yx\n" +
            "va-yz\n" +
            "az-it\n" +
            "ej-nw\n" +
            "lb-kt\n" +
            "uc-ic\n" +
            "bv-ru\n" +
            "uc-mz\n" +
            "zv-bc\n" +
            "ng-ds\n" +
            "rh-le\n" +
            "xt-ny\n" +
            "fs-gq\n" +
            "nl-fe\n" +
            "nq-lq\n" +
            "cr-sq\n" +
            "hz-pc\n" +
            "id-gv\n" +
            "dl-qu\n" +
            "nv-ew\n" +
            "jp-ce\n" +
            "pe-ys\n" +
            "ak-by\n" +
            "fl-hd\n" +
            "fx-pk\n" +
            "wm-lb\n" +
            "gh-kn\n" +
            "il-xv\n" +
            "sz-kr\n" +
            "pc-td\n" +
            "np-wt\n" +
            "hl-yq\n" +
            "bt-pm\n" +
            "ng-eg\n" +
            "pn-ra\n" +
            "gy-nw\n" +
            "cw-ez\n" +
            "zb-bi\n" +
            "zm-ji\n" +
            "ff-nd\n" +
            "ti-bz\n" +
            "gu-sy\n" +
            "rb-cr\n" +
            "xl-rb\n" +
            "xx-iq\n" +
            "po-xr\n" +
            "ws-yo\n" +
            "wl-vk\n" +
            "ws-dd\n" +
            "gy-va\n" +
            "eh-gi\n" +
            "im-fv\n" +
            "px-xc\n" +
            "ra-kc\n" +
            "xt-yi\n" +
            "ug-gj\n" +
            "ed-ty\n" +
            "pf-ww\n" +
            "yx-br\n" +
            "zg-yv\n" +
            "cq-oo\n" +
            "jt-my\n" +
            "vq-eh\n" +
            "ze-uv\n" +
            "mz-ki\n" +
            "jv-ej\n" +
            "fo-vs\n" +
            "gr-xl\n" +
            "ig-ol\n" +
            "he-oj\n" +
            "ki-bm\n" +
            "db-wi\n" +
            "tl-su\n" +
            "fx-pg\n" +
            "av-ll\n" +
            "rk-nd\n" +
            "at-lu\n" +
            "bc-gi\n" +
            "fs-vv\n" +
            "aw-bj\n" +
            "yu-xa\n" +
            "hv-cs\n" +
            "as-na\n" +
            "qy-bs\n" +
            "qs-rr\n" +
            "ub-jf\n" +
            "ev-um\n" +
            "kl-yb\n" +
            "bu-us\n" +
            "kc-pm\n" +
            "ra-ge\n" +
            "vu-yi\n" +
            "zs-br\n" +
            "rb-oo\n" +
            "by-yk\n" +
            "pz-vo\n" +
            "ub-ki\n" +
            "mo-sv\n" +
            "kq-dn\n" +
            "bi-ue\n" +
            "ew-sw\n" +
            "xt-et\n" +
            "dm-nx\n" +
            "tp-ja\n" +
            "pw-ax\n" +
            "hz-az\n" +
            "be-bw\n" +
            "fi-eh\n" +
            "ea-qe\n" +
            "pv-cm\n" +
            "ls-uj\n" +
            "gm-wo\n" +
            "kz-dx\n" +
            "nw-xj\n" +
            "pc-ty\n" +
            "ki-ys\n" +
            "mq-tl\n" +
            "tt-xa\n" +
            "ah-ql\n" +
            "dh-ib\n" +
            "qp-dk\n" +
            "hf-hc\n" +
            "bn-ts\n" +
            "jx-rc\n" +
            "og-oc\n" +
            "lt-uw\n" +
            "uc-gm\n" +
            "vy-sx\n" +
            "he-ng\n" +
            "ck-wr\n" +
            "fe-zb\n" +
            "gc-tt\n" +
            "at-gl\n" +
            "wk-gh\n" +
            "pg-ev\n" +
            "nx-gx\n" +
            "bf-nn\n" +
            "aj-as\n" +
            "xc-yi\n" +
            "bt-kc\n" +
            "dn-dy\n" +
            "sh-sj\n" +
            "da-ht\n" +
            "lh-zl\n" +
            "rb-cq\n" +
            "rp-in\n" +
            "al-ez\n" +
            "dq-if\n" +
            "ts-nh\n" +
            "gb-lt\n" +
            "ts-mx\n" +
            "re-qx\n" +
            "lv-mp\n" +
            "tb-qw\n" +
            "gd-mv\n" +
            "gn-uv\n" +
            "lg-qn\n" +
            "xg-fl\n" +
            "kt-ob\n" +
            "yh-ob\n" +
            "lr-id\n" +
            "vj-ut\n" +
            "az-bk\n" +
            "oq-nc\n" +
            "nq-rt\n" +
            "jx-sn\n" +
            "zn-rp\n" +
            "fj-ro\n" +
            "sw-ym\n" +
            "mh-si\n" +
            "cm-br\n" +
            "va-ci\n" +
            "fd-oz\n" +
            "ch-yv\n" +
            "ti-ej\n" +
            "qz-co\n" +
            "fx-ea\n" +
            "xu-ig\n" +
            "hu-vg\n" +
            "wi-rh\n" +
            "ml-lc\n" +
            "yd-xu\n" +
            "zk-bk\n" +
            "rj-ro\n" +
            "xe-lx\n" +
            "mo-ug\n" +
            "vu-xc\n" +
            "hv-dq\n" +
            "xg-ri\n" +
            "xh-py\n" +
            "ew-qw\n" +
            "sr-kt\n" +
            "vr-tk\n" +
            "vu-kk\n" +
            "lu-fv\n" +
            "xc-lm\n" +
            "mx-ls\n" +
            "le-db\n" +
            "aw-ff\n" +
            "vh-zg\n" +
            "kr-cb\n" +
            "rt-ne\n" +
            "ny-et\n" +
            "df-vx\n" +
            "sm-mg\n" +
            "lu-bl\n" +
            "zk-nc\n" +
            "an-gu\n" +
            "lb-dx\n" +
            "xw-vv\n" +
            "ul-bs\n" +
            "ub-pe\n" +
            "og-wt\n" +
            "pg-wz\n" +
            "mb-is\n" +
            "pf-dq\n" +
            "mp-eh\n" +
            "an-vd\n" +
            "qs-py\n" +
            "oz-ex\n" +
            "cq-mg\n" +
            "ne-cv\n" +
            "ui-ro\n" +
            "ly-qh\n" +
            "hs-br\n" +
            "sg-qh\n" +
            "xw-fs\n" +
            "sg-xt\n" +
            "ib-mb\n" +
            "sp-lm\n" +
            "yb-av\n" +
            "ao-qk\n" +
            "gh-cw\n" +
            "uj-ts\n" +
            "kq-pf\n" +
            "gh-ez\n" +
            "ch-jq\n" +
            "tl-xf\n" +
            "gu-xv\n" +
            "by-up\n" +
            "bi-yd\n" +
            "sy-an\n" +
            "ca-lc\n" +
            "cu-hg\n" +
            "eg-ai\n" +
            "gb-oq\n" +
            "qw-ym\n" +
            "jo-kb\n" +
            "so-su\n" +
            "nu-xr\n" +
            "ja-rh\n" +
            "xf-dp\n" +
            "wl-bg\n" +
            "ru-ny\n" +
            "xf-ic\n" +
            "yr-ex\n" +
            "uw-gb\n" +
            "vo-vb\n" +
            "fi-lv\n" +
            "ql-nq\n" +
            "eo-no\n" +
            "le-yv\n" +
            "cw-nn\n" +
            "qm-ou\n" +
            "uc-si\n" +
            "ja-np\n" +
            "oa-ys\n" +
            "nk-gu\n" +
            "jc-vr\n" +
            "yb-eo\n" +
            "vw-sp\n" +
            "no-kl\n" +
            "yn-bs\n" +
            "fl-dn\n" +
            "we-lk\n" +
            "hv-if\n" +
            "zf-wh\n" +
            "hv-jb\n" +
            "rh-jq\n" +
            "up-yl\n" +
            "xp-fy\n" +
            "px-iw\n" +
            "ue-xu\n" +
            "gr-lb\n" +
            "uf-wz\n" +
            "bc-ey\n" +
            "dg-mt\n" +
            "nf-zj\n" +
            "yx-ou\n" +
            "oa-bm\n" +
            "nq-ah\n" +
            "oh-id\n" +
            "qs-zb\n" +
            "mf-vy\n" +
            "rh-de\n" +
            "hx-hl\n" +
            "mo-mq\n" +
            "iu-pt\n" +
            "oq-nu\n" +
            "zh-dt\n" +
            "ul-gc\n" +
            "pa-zv\n" +
            "in-eg\n" +
            "vf-he\n" +
            "xe-ez\n" +
            "gd-zm\n" +
            "ry-ci\n" +
            "yo-dd\n" +
            "xn-tm\n" +
            "vn-yl\n" +
            "ry-wh\n" +
            "uj-sh\n" +
            "az-zz\n" +
            "sj-mx\n" +
            "yb-oj\n" +
            "us-zt\n" +
            "wt-fa\n" +
            "sw-wh\n" +
            "ne-vg\n" +
            "be-ij\n" +
            "vx-mc\n" +
            "tm-gx\n" +
            "jc-dg\n" +
            "hb-dg\n" +
            "nh-ux\n" +
            "jo-wk\n" +
            "iq-yi\n" +
            "ci-kc\n" +
            "gd-qn\n" +
            "qy-ul\n" +
            "sn-ew\n" +
            "xi-ga\n" +
            "gr-fj\n" +
            "lu-nr\n" +
            "up-hg\n" +
            "fo-zl\n" +
            "hf-pm\n" +
            "bx-co\n" +
            "oh-st\n" +
            "mt-nf\n" +
            "ow-bm\n" +
            "oj-ll\n" +
            "ji-qn\n" +
            "sg-ny\n" +
            "cl-dg\n" +
            "mp-pe\n" +
            "ux-ty\n" +
            "dm-jg\n" +
            "dl-ur\n" +
            "jl-sd\n" +
            "bs-fu\n" +
            "zl-kz\n" +
            "dn-vd\n" +
            "pc-it\n" +
            "yr-gv\n" +
            "qs-ue\n" +
            "jb-dq\n" +
            "jx-vx\n" +
            "lg-jt\n" +
            "rh-wv\n" +
            "iu-ta\n" +
            "qe-ff\n" +
            "lh-kz\n" +
            "my-mv\n" +
            "sa-yl\n" +
            "xw-nl\n" +
            "bk-dq\n" +
            "mo-fj\n" +
            "io-kq\n" +
            "yg-wc\n" +
            "ct-bz\n" +
            "zw-bx\n" +
            "aw-qe\n" +
            "wq-fx\n" +
            "sd-on\n" +
            "vb-wr\n" +
            "yu-vi\n" +
            "pr-ry\n" +
            "tw-rj\n" +
            "cw-xk\n" +
            "zs-nd\n" +
            "lh-ob\n" +
            "wg-qz\n" +
            "ds-kl\n" +
            "li-lg\n" +
            "qw-rl\n" +
            "sf-hl\n" +
            "gq-au\n" +
            "gx-xn\n" +
            "zh-fp\n" +
            "eg-hg\n" +
            "bu-vc\n" +
            "zk-hq\n" +
            "hd-cj\n" +
            "bk-cf\n" +
            "ot-mr\n" +
            "rs-rt\n" +
            "rc-qj\n" +
            "pw-le\n" +
            "ae-or\n" +
            "mf-tj\n" +
            "qe-nd\n" +
            "nr-im\n" +
            "yx-ey\n" +
            "ma-fa\n" +
            "gb-zp\n" +
            "ga-sy\n" +
            "cb-zq\n" +
            "fa-np\n" +
            "wh-rl\n" +
            "nd-fx\n" +
            "ed-ux\n" +
            "ra-hf\n" +
            "eg-up\n" +
            "cb-pg\n" +
            "ae-nu\n" +
            "mo-xf\n" +
            "ej-xw\n" +
            "xl-rj\n" +
            "cj-ri\n" +
            "gr-mj\n" +
            "zi-dr\n" +
            "wn-vb\n" +
            "ge-bt\n" +
            "ab-kq\n" +
            "np-hs\n" +
            "nb-da\n" +
            "yx-ir\n" +
            "xq-bu\n" +
            "xw-as\n" +
            "tb-wh\n" +
            "fs-nl\n" +
            "yu-gc\n" +
            "zc-jr\n" +
            "iv-yt\n" +
            "av-vf\n" +
            "an-il\n" +
            "yi-ks\n" +
            "ci-gy\n" +
            "bi-mh\n" +
            "cm-ma\n" +
            "rr-vk\n" +
            "kf-fs\n" +
            "po-gb\n" +
            "fj-zh\n" +
            "bt-ju\n" +
            "xe-hw\n" +
            "ha-sh\n" +
            "zp-uw\n" +
            "bj-pk\n" +
            "ou-ir\n" +
            "zg-wi\n" +
            "br-fa\n" +
            "qd-jg\n" +
            "bt-hc\n" +
            "py-ig\n" +
            "wc-ux\n" +
            "bs-tt\n" +
            "qy-yu\n" +
            "xp-al\n" +
            "ex-vl\n" +
            "fh-dl\n" +
            "sa-hq\n" +
            "kb-ub\n" +
            "tw-ml\n" +
            "ws-hb\n" +
            "em-vq\n" +
            "lt-nc\n" +
            "qc-mf\n" +
            "zb-ol\n" +
            "zc-td\n" +
            "gg-ev\n" +
            "ch-wv\n" +
            "rb-bv\n" +
            "zy-mv\n" +
            "vx-mk\n" +
            "ih-vg\n" +
            "fa-og\n" +
            "xk-sk\n" +
            "hc-ra\n" +
            "ca-yu\n" +
            "px-vw\n" +
            "xy-dl\n" +
            "lv-eh\n" +
            "wi-rw\n" +
            "mv-lg\n" +
            "sb-ui\n" +
            "cn-xq\n" +
            "nq-jr\n" +
            "iw-vw\n" +
            "ww-hb\n" +
            "ib-is\n" +
            "aj-jn\n" +
            "sx-qc\n" +
            "ox-mp\n" +
            "us-ht\n" +
            "br-np\n" +
            "lb-sr\n" +
            "xv-lc\n" +
            "go-sa\n" +
            "dr-cw\n" +
            "yn-ys\n" +
            "jb-oc\n" +
            "sz-rq\n" +
            "zz-nh\n" +
            "ro-tw\n" +
            "yz-ry\n" +
            "ka-ep\n" +
            "gj-sv\n" +
            "pt-mg\n" +
            "yd-mh\n" +
            "gr-fp\n" +
            "lu-it\n" +
            "kc-xh\n" +
            "fz-kx\n" +
            "fu-xa\n" +
            "mi-sg\n" +
            "tj-nr\n" +
            "ls-ha\n" +
            "el-hs\n" +
            "xw-na\n" +
            "zm-vt\n" +
            "vh-wi\n" +
            "xg-js\n" +
            "ox-vq\n" +
            "pk-rk\n" +
            "wc-zz\n" +
            "nu-po\n" +
            "sb-mj\n" +
            "ef-oh\n" +
            "qn-jt\n" +
            "vv-au\n" +
            "tn-xh\n" +
            "fv-tj\n" +
            "zf-ij\n" +
            "po-uw\n" +
            "we-jb\n" +
            "yx-ek\n" +
            "om-my\n" +
            "zn-up\n" +
            "qb-cb\n" +
            "ue-wl\n" +
            "zp-oq\n" +
            "ze-et\n" +
            "ah-cv\n" +
            "sw-ij\n" +
            "dk-nz\n" +
            "ha-ts\n" +
            "ru-xt\n" +
            "dy-ri\n" +
            "kq-us\n" +
            "yd-zb\n" +
            "vr-qp\n" +
            "yk-so\n" +
            "vn-ei\n" +
            "rc-mk\n" +
            "xe-kn\n" +
            "bg-fw\n" +
            "fo-dx\n" +
            "np-pv\n" +
            "qu-gk\n" +
            "ab-bu\n" +
            "qq-ai\n" +
            "qe-lj\n" +
            "jw-fo\n" +
            "vn-hg\n" +
            "we-bk\n" +
            "nw-pr\n" +
            "fl-vd\n" +
            "qq-kt\n" +
            "ui-mj\n" +
            "lj-ea\n" +
            "zm-jt\n" +
            "vt-zt\n" +
            "af-ks\n" +
            "dq-cs\n" +
            "sv-tl\n" +
            "nb-xq\n" +
            "ue-rr\n" +
            "gl-mf\n" +
            "cw-xe\n" +
            "dg-nf\n" +
            "tm-wr\n" +
            "hp-nz\n" +
            "hb-vr\n" +
            "du-pv\n" +
            "yl-eg\n" +
            "ky-ur\n" +
            "pe-my\n" +
            "dm-pz\n" +
            "kd-dg\n" +
            "dc-jj\n" +
            "as-fe\n" +
            "yr-oh\n" +
            "gb-ae\n" +
            "es-gx\n" +
            "go-hv\n" +
            "eg-vn\n" +
            "lh-sr\n" +
            "ej-ry\n" +
            "mq-xf\n" +
            "ur-xy\n" +
            "jw-yh\n" +
            "ch-wp\n" +
            "hx-mk\n" +
            "vv-kf\n" +
            "ry-dc\n" +
            "sd-ut\n" +
            "og-np\n" +
            "aj-au\n" +
            "ru-nz\n" +
            "ll-yb\n" +
            "ev-qb\n" +
            "kt-wm\n" +
            "rk-ea\n" +
            "bn-gp\n" +
            "zy-in\n" +
            "nn-qm\n" +
            "hd-bz\n" +
            "qb-sz\n" +
            "ir-hj\n" +
            "vl-fd\n" +
            "rw-ch\n" +
            "wt-hs\n" +
            "uc-fq\n" +
            "rw-db\n" +
            "oe-ir\n" +
            "ui-vi\n" +
            "lg-ji\n" +
            "fq-xi\n" +
            "nv-be\n" +
            "ml-il\n" +
            "yy-vc\n" +
            "yq-ku\n" +
            "qm-bm\n" +
            "sz-ev\n" +
            "qk-re\n" +
            "bi-wl\n" +
            "em-eh\n" +
            "hc-rv\n" +
            "fy-sk\n" +
            "gu-ca\n" +
            "ii-cv\n" +
            "qw-be\n" +
            "fa-pv\n" +
            "fp-cl\n" +
            "xi-gm\n" +
            "ze-ny\n" +
            "ob-jw\n" +
            "mb-dh\n" +
            "at-st\n" +
            "yk-su\n" +
            "sh-jz\n" +
            "vk-xu\n" +
            "tw-cl\n" +
            "ml-xv\n" +
            "lc-gu\n" +
            "bx-fh\n" +
            "fv-oi\n" +
            "wz-zq\n" +
            "lh-dw\n" +
            "fn-tl\n" +
            "ki-gq\n" +
            "ka-ju\n" +
            "cs-cf\n" +
            "at-tj\n" +
            "df-qj\n" +
            "ns-qk\n" +
            "wv-rw\n" +
            "jx-qj\n" +
            "ee-ri\n" +
            "pe-kb\n" +
            "no-ll\n" +
            "sp-vu\n" +
            "rz-ol\n" +
            "kf-aj\n" +
            "yy-ml\n" +
            "up-ei\n" +
            "vv-qy\n" +
            "um-mb\n" +
            "np-ma\n" +
            "rc-sf\n" +
            "sk-qb\n" +
            "gg-ph\n" +
            "qo-nz\n" +
            "on-vj\n" +
            "fs-as\n" +
            "fl-dy\n" +
            "yu-tt\n" +
            "cf-zk\n" +
            "ck-xn\n" +
            "ub-oa\n" +
            "au-jn\n" +
            "ed-az\n" +
            "nf-ws\n" +
            "oq-ae\n" +
            "ae-ni\n" +
            "pe-wk\n" +
            "ys-ur\n" +
            "dp-su\n" +
            "cl-dt\n" +
            "ao-ih\n" +
            "ma-sh\n" +
            "dt-fp\n" +
            "um-jg\n" +
            "hj-ek\n" +
            "pn-pl\n" +
            "dy-cj\n" +
            "ky-co\n" +
            "vv-aj\n" +
            "vb-es\n" +
            "ud-fy\n" +
            "pu-ii\n" +
            "ko-fz\n" +
            "hp-fx\n" +
            "ab-us\n" +
            "my-gd\n" +
            "dv-as\n" +
            "xu-wl\n" +
            "gk-ww\n" +
            "sn-vx\n" +
            "rq-kr\n" +
            "vl-lw\n" +
            "yy-gu\n" +
            "mx-jz\n" +
            "uz-fh\n" +
            "nm-yu\n" +
            "bi-rr\n" +
            "mp-gn\n" +
            "pm-ra\n" +
            "gd-om\n" +
            "ma-jp\n" +
            "xk-lx\n" +
            "mj-ro\n" +
            "ud-al\n" +
            "ee-fl\n" +
            "ju-ge\n" +
            "yq-qj\n" +
            "xd-cq\n" +
            "gj-yk\n" +
            "vo-nx\n" +
            "kr-wz\n" +
            "hx-mc\n" +
            "pm-xh\n" +
            "uf-qb\n" +
            "gc-qy\n" +
            "dp-sv\n" +
            "fw-bj\n" +
            "rl-zf\n" +
            "vx-yq\n" +
            "ld-eb\n" +
            "uw-du\n" +
            "jr-rt\n" +
            "zf-nv\n" +
            "gq-na\n" +
            "lc-ga\n" +
            "ci-jj\n" +
            "ef-oz\n" +
            "dn-xg\n" +
            "na-aj\n" +
            "kd-tk\n" +
            "tp-jg\n" +
            "yh-sr\n" +
            "fe-dv\n" +
            "jq-vh\n" +
            "dm-es\n" +
            "hh-bv\n" +
            "zk-lk\n" +
            "sd-wn\n" +
            "rb-sm\n" +
            "ov-kr\n" +
            "br-ce\n" +
            "lu-mf\n" +
            "hv-lk\n" +
            "ak-yl\n" +
            "mp-cr\n" +
            "ob-dx\n" +
            "dn-dw\n" +
            "my-ag\n" +
            "yq-sn\n" +
            "yd-ig\n" +
            "vi-ot\n" +
            "cf-sa\n" +
            "kn-hw\n" +
            "up-rp\n" +
            "on-ut\n" +
            "fz-ae\n" +
            "hh-oo\n" +
            "jm-zf\n" +
            "ub-wk\n" +
            "vs-vc\n" +
            "ka-xh\n" +
            "dg-yh\n" +
            "wr-dm\n" +
            "np-oc\n" +
            "yo-kd\n" +
            "fp-rj\n" +
            "gd-zt\n" +
            "lq-cv\n" +
            "it-zz\n" +
            "jv-ti\n" +
            "ck-pz\n" +
            "jp-br\n" +
            "au-nl\n" +
            "sy-il\n" +
            "um-ja\n" +
            "gp-hl\n" +
            "aw-lj\n" +
            "hb-kd\n" +
            "dv-nl\n" +
            "cq-hh\n" +
            "bc-ek\n" +
            "fq-wn\n" +
            "kr-gg\n" +
            "rq-dq\n" +
            "ez-sk\n" +
            "dr-cq\n" +
            "ur-qu\n" +
            "ht-xq\n" +
            "an-ml\n" +
            "gi-vq\n" +
            "ne-jr\n" +
            "af-xx\n" +
            "zm-lg\n" +
            "vj-ic\n" +
            "sq-fi\n" +
            "xn-pt\n" +
            "et-ru\n" +
            "kk-px\n" +
            "sn-df\n" +
            "hl-mk\n" +
            "ii-nq\n" +
            "mt-dd\n" +
            "et-mi\n" +
            "mf-im\n" +
            "zn-eg\n" +
            "ep-ju\n" +
            "li-vt\n" +
            "li-qn\n" +
            "ow-mz\n" +
            "fh-qz\n" +
            "td-ld\n" +
            "zq-pg\n" +
            "nq-ne\n" +
            "yy-ca\n" +
            "gp-yt\n" +
            "sb-hd\n" +
            "bk-if\n" +
            "kk-xc\n" +
            "ah-pd\n" +
            "uz-co\n" +
            "hq-go\n" +
            "fw-xb\n" +
            "gv-ef\n" +
            "zs-wq\n" +
            "ct-fl\n" +
            "mf-ih\n" +
            "qz-uz\n" +
            "si-gm\n" +
            "wh-nv\n" +
            "bn-sh\n" +
            "gs-xf\n" +
            "im-gl\n" +
            "vc-xv\n" +
            "ni-zp\n" +
            "oe-bc\n" +
            "pd-ql\n" +
            "bw-jm\n" +
            "ro-xl\n" +
            "tk-jc\n" +
            "jn-kf\n" +
            "um-mu\n" +
            "qs-mh\n" +
            "bl-oi\n" +
            "zn-ie\n" +
            "jv-va\n" +
            "dd-tk\n" +
            "lq-ii\n" +
            "ds-no\n" +
            "pm-zi\n" +
            "zc-pd\n" +
            "fu-nm\n" +
            "kl-he\n" +
            "ll-ep\n" +
            "bk-sa\n" +
            "zw-qz\n" +
            "il-vc\n" +
            "yk-vs\n" +
            "qd-mb\n" +
            "vw-xx\n" +
            "go-lk\n" +
            "ax-ao\n" +
            "cs-lk\n" +
            "nu-uw\n" +
            "dg-yo\n" +
            "zb-ue\n" +
            "iq-xc\n" +
            "zm-ag\n" +
            "wq-pk\n" +
            "cn-ze\n" +
            "zm-ex\n" +
            "ux-yv\n" +
            "dy-ct\n" +
            "uf-jr\n" +
            "yv-wp\n" +
            "pu-jr\n" +
            "tw-dt\n" +
            "zz-hu\n" +
            "iu-zi\n" +
            "dy-hd\n" +
            "ex-lr\n" +
            "zh-rj\n" +
            "or-nu\n" +
            "jc-dd\n" +
            "ns-hu\n" +
            "qp-dd\n" +
            "mg-bv\n" +
            "sh-gp\n" +
            "on-wo\n" +
            "yx-pa\n" +
            "bz-ri\n" +
            "sg-nz\n" +
            "sf-sn\n" +
            "lk-if\n" +
            "wt-br\n" +
            "hu-pw\n" +
            "gj-gs\n" +
            "mh-xu\n" +
            "kc-ep\n" +
            "yk-mq\n" +
            "ig-ue\n" +
            "dl-qz\n" +
            "rp-yl\n" +
            "yv-de\n" +
            "ae-du\n" +
            "ko-kx\n" +
            "na-vv\n" +
            "xv-nk\n" +
            "db-ch\n" +
            "mx-uj\n" +
            "xd-pa\n" +
            "rq-pg\n" +
            "dk-ny\n" +
            "zl-sr\n" +
            "bs-ot\n" +
            "cv-jr\n" +
            "sp-xc\n" +
            "hg-ei\n" +
            "ie-yu\n" +
            "nx-tm\n" +
            "xi-jl\n" +
            "ev-wz\n" +
            "jc-hb\n" +
            "ib-fz\n" +
            "fs-au\n" +
            "ur-qz\n" +
            "gs-fn\n" +
            "gv-vl\n" +
            "dh-tp\n" +
            "rk-lj\n" +
            "sf-wq\n" +
            "xb-qx\n" +
            "du-gb\n" +
            "lg-jj\n" +
            "ca-vc\n" +
            "yl-in\n" +
            "zk-we\n" +
            "pk-ff\n" +
            "ck-nx\n" +
            "lq-ah\n" +
            "yd-qs\n" +
            "ti-jj\n" +
            "dl-uz\n" +
            "oe-hj\n" +
            "xk-ud\n" +
            "tb-sw\n" +
            "yy-ga\n" +
            "lq-rs\n" +
            "ey-zv\n" +
            "gk-pf\n" +
            "vv-as\n" +
            "ux-zz\n" +
            "ro-dt\n" +
            "tl-cr\n" +
            "pl-qz\n" +
            "ao-re\n" +
            "sr-fo\n" +
            "kl-ll\n" +
            "vx-rz\n" +
            "gx-vb\n" +
            "hw-gh\n" +
            "ym-bw\n" +
            "ed-ld\n" +
            "yn-ub\n" +
            "gh-xp\n" +
            "vu-iw\n" +
            "lm-iw\n" +
            "zn-by\n" +
            "sm-cq\n" +
            "ce-ma\n" +
            "eh-rz\n" +
            "zt-zm\n" +
            "ig-wl\n" +
            "ws-mt\n" +
            "rw-de\n" +
            "wp-de\n" +
            "xu-qs\n" +
            "gi-rz\n" +
            "pv-og\n" +
            "zl-kt\n" +
            "ld-hz\n" +
            "wz-qb\n" +
            "fa-vh\n" +
            "nf-hb\n" +
            "vx-hx\n" +
            "pg-kr\n" +
            "wg-av\n" +
            "sn-mk\n" +
            "ai-yl\n" +
            "tb-ij\n" +
            "gq-as\n" +
            "px-si\n" +
            "dh-fz\n" +
            "yz-ma\n" +
            "co-fh\n" +
            "le-de\n" +
            "qd-mu\n" +
            "hs-ma\n" +
            "wn-xi\n" +
            "dn-bz\n" +
            "oj-no\n" +
            "ns-ao\n" +
            "bj-ea\n" +
            "es-wr\n" +
            "re-ns\n" +
            "hs-fa\n" +
            "ud-xp\n" +
            "qx-kb\n" +
            "cj-fl\n" +
            "jq-db\n" +
            "bj-hp\n" +
            "gq-xg\n" +
            "dc-nw\n" +
            "xv-ca\n" +
            "wn-wo\n" +
            "bw-sw\n" +
            "yg-nh\n" +
            "vi-fu\n" +
            "pk-zs\n" +
            "pm-ju\n" +
            "fy-xe\n" +
            "qb-ph\n" +
            "fz-um\n" +
            "zh-tw\n" +
            "ne-ii\n" +
            "im-oi\n" +
            "bk-lk\n" +
            "nn-hj\n" +
            "jt-zt\n" +
            "ds-ki\n" +
            "vo-xn\n" +
            "ww-us\n" +
            "zv-oe\n" +
            "vb-ho\n" +
            "gh-fy\n" +
            "to-dm\n" +
            "mv-jt\n" +
            "cc-wg\n" +
            "ze-dk\n" +
            "oj-cc\n" +
            "ub-bm\n" +
            "ie-ul\n" +
            "cu-nz\n" +
            "fp-fj\n" +
            "lr-oh\n" +
            "rh-wp\n" +
            "iq-px\n" +
            "rc-hx\n" +
            "hz-it\n" +
            "sk-al\n" +
            "rc-go\n" +
            "gc-nm\n" +
            "lv-em\n" +
            "ns-ae\n" +
            "nr-ah\n" +
            "qj-vx\n" +
            "ir-ey\n" +
            "mr-qy\n" +
            "br-el\n" +
            "jv-pr\n" +
            "re-pw\n" +
            "hq-cs\n" +
            "eo-cc\n" +
            "iv-gp\n" +
            "xk-xe\n" +
            "ql-rs\n" +
            "oc-pv\n" +
            "dk-qo\n" +
            "ru-dk\n" +
            "jb-bk\n" +
            "pz-ho\n" +
            "cu-mi\n" +
            "zf-ym\n" +
            "ow-wk\n" +
            "xp-xk\n" +
            "ic-si\n" +
            "pv-br\n" +
            "gx-pz\n" +
            "cf-dq\n" +
            "oi-tj\n" +
            "zp-or\n" +
            "ug-dp\n" +
            "gr-zh\n" +
            "wt-pv\n" +
            "tw-gr\n" +
            "cr-gn\n" +
            "vr-ws\n" +
            "ck-gx\n" +
            "jf-kb\n" +
            "ut-wn\n" +
            "oo-xd\n" +
            "qx-fw\n" +
            "qz-xy\n" +
            "oo-mg\n" +
            "fn-mo\n" +
            "yo-qp\n" +
            "nn-oe\n" +
            "pl-co\n" +
            "ws-kd\n" +
            "gu-oo\n" +
            "fi-uv\n" +
            "gq-xw\n" +
            "rp-ak\n" +
            "tj-lu\n" +
            "bf-ek\n" +
            "kx-qd\n" +
            "xj-ej\n" +
            "xv-sy\n" +
            "zp-po\n" +
            "zl-ob\n" +
            "ts-jz\n" +
            "pd-jr\n" +
            "dk-sg\n" +
            "xj-jv\n" +
            "ck-ho\n" +
            "dv-kf\n" +
            "tt-vi\n" +
            "kf-sd\n" +
            "lw-if\n" +
            "wk-ki\n" +
            "ku-df\n" +
            "ez-pl\n" +
            "tm-as\n" +
            "kb-yn\n" +
            "oo-sm\n" +
            "kz-kt\n" +
            "yx-oe\n" +
            "pz-xn\n" +
            "xr-nc\n" +
            "zb-mh\n" +
            "bm-mz\n" +
            "hh-mg\n" +
            "ef-kr\n" +
            "ak-in\n" +
            "ld-pc\n" +
            "ww-bu\n" +
            "ni-uw\n" +
            "vj-jl\n" +
            "cb-ph\n" +
            "kq-da\n" +
            "mx-iv\n" +
            "rp-ei\n" +
            "jz-wx\n" +
            "mk-qj\n" +
            "hp-zs\n" +
            "vh-rh\n" +
            "sd-gm\n" +
            "qe-pk\n" +
            "dr-ta\n" +
            "rv-pm\n" +
            "gy-jv\n" +
            "xy-pl\n" +
            "da-cn\n" +
            "cu-dk\n" +
            "yv-rw\n" +
            "ew-wh\n" +
            "ja-jg\n" +
            "gm-ju\n" +
            "xd-bv\n" +
            "ue-yd\n" +
            "to-ck\n" +
            "dn-cj\n" +
            "ru-cu\n" +
            "kb-ow\n" +
            "jx-sf\n" +
            "gi-gn\n" +
            "xv-nu\n" +
            "mu-wm\n" +
            "hv-we\n" +
            "pv-ma\n" +
            "qq-dx\n" +
            "ah-zc\n" +
            "bv-ta\n" +
            "nv-bw\n" +
            "yr-ef\n" +
            "hl-jx\n" +
            "ts-sh\n" +
            "ne-pu\n" +
            "at-vy\n" +
            "zk-jb\n" +
            "ch-le\n" +
            "mq-jc\n" +
            "zi-oo\n" +
            "ak-ei\n" +
            "uz-qu\n" +
            "mt-tk\n" +
            "dh-qd\n" +
            "jn-na\n" +
            "lq-ne\n" +
            "kk-kt\n" +
            "ai-ht\n" +
            "lg-my\n" +
            "bs-mr\n" +
            "rp-zy\n" +
            "ao-bg\n" +
            "wi-le\n" +
            "wv-jq\n" +
            "dt-ui\n" +
            "hs-cv\n" +
            "co-jn\n" +
            "jg-ko\n" +
            "ks-iw\n" +
            "eb-oz\n" +
            "li-av\n" +
            "wi-mc\n" +
            "gk-ht\n" +
            "dc-va\n" +
            "qh-sy\n" +
            "fl-ws\n" +
            "na-kf\n" +
            "lb-fo\n" +
            "fz-is\n" +
            "vw-ks\n" +
            "uv-sq\n" +
            "yz-nw\n" +
            "tn-ka\n" +
            "jo-bm\n" +
            "ls-im\n" +
            "vy-im\n" +
            "st-ef\n" +
            "oh-lw\n" +
            "ce-el\n" +
            "ry-ti\n" +
            "zm-my\n" +
            "sj-ts\n" +
            "xj-bu\n" +
            "ai-hg\n" +
            "ku-rc\n" +
            "qc-gl\n" +
            "xb-re\n" +
            "vq-ut\n" +
            "oc-ma\n" +
            "zg-lk\n" +
            "zs-ff\n" +
            "vt-ag\n" +
            "ry-nw\n" +
            "zy-by\n" +
            "mb-tp\n" +
            "nb-gk\n" +
            "gp-mx\n" +
            "jp-hs\n" +
            "yh-zl\n" +
            "ub-nw\n" +
            "ph-zq\n" +
            "rc-mc\n" +
            "kn-xk\n" +
            "ag-ct\n" +
            "sz-ov\n" +
            "gc-bs\n" +
            "vw-af\n" +
            "ut-jl\n" +
            "at-fv\n" +
            "vq-lv\n" +
            "yd-py\n" +
            "fp-xq\n" +
            "tl-yk\n" +
            "xw-au\n" +
            "ux-az\n" +
            "eo-vf\n" +
            "oq-xr\n" +
            "gy-xj\n" +
            "pl-uz\n" +
            "mi-dk\n" +
            "ov-qb\n" +
            "zy-ai\n" +
            "jl-ic\n" +
            "dl-co\n" +
            "vn-up\n" +
            "nz-ny\n" +
            "zl-jw\n" +
            "dc-lh\n" +
            "sr-jw\n" +
            "jw-lh\n" +
            "zp-xr\n" +
            "nm-tt\n" +
            "ck-vb\n" +
            "zq-qj\n" +
            "ow-oa\n" +
            "su-mo\n" +
            "an-xv\n" +
            "ut-ic\n" +
            "iv-ha\n" +
            "yt-uj\n" +
            "po-nc\n" +
            "ao-hu\n" +
            "pt-oo\n" +
            "mh-rr\n" +
            "ch-rh\n" +
            "wo-jl\n" +
            "hz-td\n" +
            "jt-ji\n" +
            "zg-wv\n" +
            "by-vn\n" +
            "lm-yi\n" +
            "zi-ta\n" +
            "bx-ur\n" +
            "kc-tn\n" +
            "fu-gc\n" +
            "wc-ld\n" +
            "ei-af\n" +
            "zq-qb\n" +
            "ui-zh\n" +
            "yk-mo\n" +
            "ed-yg\n" +
            "hv-cf\n" +
            "td-it\n" +
            "mt-qp\n" +
            "tl-dp\n" +
            "mb-fz\n" +
            "vs-ca\n" +
            "ef-ex\n" +
            "ey-au\n" +
            "eo-ng\n" +
            "jf-ys\n" +
            "pt-xd\n" +
            "if-hq\n" +
            "hj-ey\n" +
            "pf-da\n" +
            "kc-rv\n" +
            "is-tp\n" +
            "cc-kl\n" +
            "pe-jo\n" +
            "qw-nv\n" +
            "ku-qj\n" +
            "he-eo\n" +
            "ta-cq\n" +
            "dk-xt\n" +
            "ko-dh\n" +
            "qx-vg\n" +
            "df-jx\n" +
            "wm-dx\n" +
            "we-sa\n" +
            "zz-ld\n" +
            "wk-yn\n" +
            "ta-hh\n" +
            "bm-yn\n" +
            "cm-og\n" +
            "vu-iq\n" +
            "fn-xf\n" +
            "hc-ep\n" +
            "ra-bt\n" +
            "qh-qo\n" +
            "ju-rv\n" +
            "ui-xl\n" +
            "ab-ob\n" +
            "dy-ee\n" +
            "ih-re\n" +
            "gs-jw\n" +
            "ls-gp\n" +
            "oz-lw\n" +
            "sr-ob\n" +
            "ge-kc\n" +
            "ir-nn\n" +
            "ph-rq\n" +
            "vw-iq\n" +
            "nm-xa\n" +
            "gi-lv\n" +
            "ls-sj\n" +
            "ki-jf\n" +
            "nk-sy\n" +
            "lv-uv\n" +
            "ty-az\n" +
            "gp-ts\n" +
            "zc-lq\n" +
            "sg-et\n" +
            "vy-de\n" +
            "jm-rl\n" +
            "vn-zy\n" +
            "vl-ef\n" +
            "cl-ui\n" +
            "ij-ym\n" +
            "nb-ng\n" +
            "ee-et\n" +
            "xj-dc\n" +
            "ey-bf\n" +
            "ui-fp\n" +
            "xj-ti\n" +
            "ev-rq\n" +
            "hg-by\n" +
            "xh-ge\n" +
            "jz-iv\n" +
            "gs-su\n" +
            "fv-zp\n" +
            "il-yy\n" +
            "hw-ka\n" +
            "hf-rv\n" +
            "bk-go\n" +
            "hu-bg\n" +
            "ky-fh\n" +
            "kr-qb\n" +
            "kn-na\n" +
            "cs-if\n" +
            "ao-vx\n" +
            "qd-ko\n" +
            "wx-ts\n" +
            "jb-lk\n" +
            "fn-mq\n" +
            "hq-jb\n" +
            "pn-fh\n" +
            "pn-qu\n" +
            "zg-le\n" +
            "nu-zp\n" +
            "yb-wg\n" +
            "gm-ic\n" +
            "du-or\n" +
            "eh-uv\n" +
            "xb-ns\n" +
            "sf-ku\n" +
            "rl-be\n" +
            "xv-sp\n" +
            "cb-ev\n" +
            "hw-cw\n" +
            "gq-fe\n" +
            "zh-mj\n" +
            "qw-bw\n" +
            "ja-mb\n" +
            "np-ce\n" +
            "zh-cl\n" +
            "bw-wh\n" +
            "xq-pf\n" +
            "ih-bg\n" +
            "hq-fz\n" +
            "zk-go\n" +
            "lr-yr\n" +
            "yg-ux\n" +
            "pt-hh\n" +
            "il-nk\n" +
            "av-oj\n" +
            "mc-jx\n" +
            "hc-xh\n" +
            "va-ti\n" +
            "nv-ij\n" +
            "kk-xx\n" +
            "yo-zj\n" +
            "xy-co\n" +
            "pl-ky\n" +
            "ce-og\n" +
            "bk-cs\n" +
            "kq-ht\n" +
            "el-og\n" +
            "ib-um\n" +
            "nl-gq\n" +
            "ee-yt\n" +
            "gn-sq\n" +
            "fu-tt\n" +
            "iv-tt\n" +
            "my-zt\n" +
            "if-jb\n" +
            "nv-jm\n" +
            "ox-lv\n" +
            "kn-cw\n" +
            "nb-pf\n" +
            "tk-yo\n" +
            "hz-yg\n" +
            "sk-xp\n" +
            "jm-dy\n" +
            "io-nb\n" +
            "tm-dm\n" +
            "de-ch\n" +
            "hu-qk\n" +
            "gq-aj\n" +
            "il-rp\n" +
            "gs-mo\n" +
            "ks-sp\n" +
            "xj-ry\n" +
            "tb-nv\n" +
            "ma-og\n" +
            "ri-dw\n" +
            "ce-pv\n" +
            "xk-fy\n" +
            "ga-an\n" +
            "ht-nb\n" +
            "as-nl\n" +
            "he-ds\n" +
            "sj-gp\n" +
            "jm-ym\n" +
            "be-vt\n" +
            "by-rp\n" +
            "gr-dt\n" +
            "dv-gq\n" +
            "qp-hb\n" +
            "jz-dh\n" +
            "wh-jm\n" +
            "ou-hj\n" +
            "st-lw\n" +
            "lg-zt\n" +
            "oi-sx\n" +
            "yt-sh\n" +
            "rr-zb\n" +
            "fj-mj\n" +
            "gs-tl\n" +
            "hj-qm\n" +
            "zf-nm\n" +
            "ej-yz\n" +
            "po-ff\n" +
            "gl-fv\n" +
            "ho-vo\n" +
            "wt-el\n" +
            "nb-us\n" +
            "bg-re\n" +
            "ji-ag\n" +
            "qw-jm\n" +
            "az-wc\n" +
            "xj-ci\n" +
            "ns-bg\n" +
            "wp-rw\n" +
            "id-ex\n" +
            "xp-ez\n" +
            "zi-mg\n" +
            "rz-vq\n" +
            "on-fq\n" +
            "hp-lj\n" +
            "ch-mx\n" +
            "sa-zk\n" +
            "cu-et\n" +
            "in-ai\n" +
            "eb-lw\n" +
            "ph-xr\n" +
            "qe-hp\n" +
            "vl-wq\n" +
            "tn-ey\n" +
            "uz-ky\n" +
            "sv-gs\n" +
            "uw-oq\n" +
            "xq-us\n" +
            "va-jj\n" +
            "pe-yn\n" +
            "kk-sp\n" +
            "vb-nx\n" +
            "ha-wx\n" +
            "ub-ow\n" +
            "ds-oj\n" +
            "uf-kr\n" +
            "af-yi\n" +
            "zv-ir\n" +
            "ta-xd\n" +
            "jq-yv\n" +
            "lj-bj\n" +
            "sn-qj\n" +
            "jj-gy\n" +
            "jz-bn\n" +
            "yr-nq\n" +
            "vl-st\n" +
            "st-lr\n" +
            "pt-zi\n" +
            "df-sf\n" +
            "ou-zv\n" +
            "dr-rb\n" +
            "xr-gb\n" +
            "ff-bj\n" +
            "xn-wr\n" +
            "xu-ol\n" +
            "oz-yr\n" +
            "ds-wg\n" +
            "ui-tw\n" +
            "cn-ab\n" +
            "tm-vo\n" +
            "on-ic\n" +
            "hl-mc\n" +
            "vh-db\n" +
            "bw-rl\n" +
            "mu-is\n" +
            "if-sa\n" +
            "jz-ha\n" +
            "va-xj\n" +
            "lq-jr\n" +
            "ol-mh\n" +
            "ed-td\n" +
            "lx-ud\n" +
            "dt-sb\n" +
            "sj-lw\n" +
            "fp-xl\n" +
            "mk-hz\n" +
            "sz-cb\n" +
            "rs-rk\n" +
            "ov-uf\n" +
            "qs-wl\n" +
            "fn-sv\n" +
            "lc-an\n" +
            "zc-pu\n" +
            "wt-gv\n" +
            "um-kx\n" +
            "dx-sr\n" +
            "lg-om\n" +
            "fh-ur\n" +
            "xx-xc\n" +
            "kf-xw\n" +
            "vi-gc\n" +
            "ej-gy\n" +
            "id-oz\n" +
            "qm-ek\n" +
            "fq-yo\n" +
            "ez-hw\n" +
            "sj-bn\n" +
            "mc-qj\n" +
            "ir-ek\n" +
            "ql-xh\n" +
            "ne-ql\n" +
            "sz-uf\n" +
            "jj-nw\n" +
            "pw-xb\n" +
            "rq-gg\n" +
            "fo-lh\n" +
            "ib-jg\n" +
            "fv-sx\n" +
            "dq-sa\n" +
            "cv-nq\n" +
            "si-jl\n" +
            "tn-bt\n" +
            "wv-de\n" +
            "js-dw\n" +
            "fd-id\n" +
            "zt-om\n" +
            "eo-kl\n" +
            "nd-wq\n" +
            "jb-sa\n" +
            "il-lc\n" +
            "xe-em\n" +
            "rr-oa\n" +
            "bf-hj\n" +
            "xl-fj\n" +
            "ni-oq\n" +
            "ri-vd\n" +
            "lb-ji\n" +
            "yb-kf\n" +
            "zy-up\n" +
            "og-hu\n" +
            "zy-ak\n" +
            "ri-kl\n" +
            "ws-zj\n" +
            "bi-ij\n" +
            "mc-sn\n" +
            "vn-rp\n" +
            "gq-jn\n" +
            "gc-gy\n" +
            "ql-rt\n" +
            "vf-oj\n" +
            "ce-cm\n" +
            "kd-zj\n" +
            "ww-nb\n" +
            "fe-au\n" +
            "nq-zc\n" +
            "as-kf\n" +
            "ml-gu\n" +
            "as-au\n" +
            "fz-mu\n" +
            "rs-ne\n" +
            "eb-st\n" +
            "af-sp\n" +
            "lc-nk\n" +
            "ly-et\n" +
            "mk-yq\n" +
            "jp-wt\n" +
            "ul-mr\n" +
            "tm-to\n" +
            "ge-nl\n" +
            "om-aj\n" +
            "xl-zh\n" +
            "hq-dq\n" +
            "ni-du\n" +
            "vk-nn\n" +
            "lm-ks\n" +
            "yb-he\n" +
            "cs-jb\n" +
            "yi-px\n" +
            "dv-jn\n" +
            "iv-uj\n" +
            "ew-zf\n" +
            "fa-cm\n" +
            "vh-le\n" +
            "tp-qd\n" +
            "df-yq\n" +
            "qu-pl\n" +
            "mq-su\n" +
            "wx-sj\n" +
            "gh-xk\n" +
            "xe-al\n" +
            "da-bu\n" +
            "zh-jt\n" +
            "lc-sy\n" +
            "nr-bl\n" +
            "jt-vt\n" +
            "fd-lw\n" +
            "az-nh\n" +
            "af-px\n" +
            "cm-jp\n" +
            "nz-qh\n" +
            "yz-ci\n" +
            "vv-jn\n" +
            "wn-on\n" +
            "hd-ct\n" +
            "ni-lt\n" +
            "cj-ct\n" +
            "hb-tk\n" +
            "kr-zq\n" +
            "wc-hz\n" +
            "ro-jv\n" +
            "cb-jp\n" +
            "ur-zw\n" +
            "xv-yy\n" +
            "mr-gc\n" +
            "jo-oa\n" +
            "rv-ge\n" +
            "gl-bl\n" +
            "qm-pa\n" +
            "cw-fy\n" +
            "ug-yk\n" +
            "pe-mz\n" +
            "zk-if\n" +
            "ts-yt\n" +
            "gd-jt\n" +
            "da-gk\n" +
            "ts-iv\n" +
            "bi-py\n" +
            "fl-js\n" +
            "ux-pc\n" +
            "al-cw\n" +
            "xd-zi\n" +
            "qo-mi\n" +
            "rc-sn\n" +
            "jx-hx\n" +
            "fq-ut\n" +
            "rv-ka\n" +
            "oj-ng\n" +
            "fn-gj\n" +
            "dp-so\n" +
            "sf-hx\n" +
            "bk-hv\n" +
            "qo-ru\n" +
            "io-gk\n" +
            "gr-ui\n" +
            "ex-st\n" +
            "zn-yl\n" +
            "dw-ee\n" +
            "mk-sf\n" +
            "gx-ho\n" +
            "wt-ce\n" +
            "ew-jm\n" +
            "az-yg\n" +
            "ax-qx\n" +
            "qw-wh\n" +
            "ha-sj\n" +
            "hl-qj\n" +
            "ck-dm\n" +
            "tb-bw\n" +
            "xg-ct\n" +
            "tj-gl\n" +
            "dk-qh\n" +
            "sd-ly\n" +
            "vq-cr\n" +
            "zg-wp\n" +
            "oe-bf\n" +
            "bl-fv\n" +
            "ir-pa\n" +
            "da-ab\n" +
            "sb-fj\n" +
            "sg-ze\n" +
            "ht-ww\n" +
            "bv-oo\n" +
            "pl-fh\n" +
            "oc-el\n" +
            "ni-nc\n" +
            "ae-nc\n" +
            "nb-ab\n" +
            "sj-iv\n" +
            "ld-it\n" +
            "zk-dq\n" +
            "nb-kq\n" +
            "pr-ti\n" +
            "gp-uj\n" +
            "ee-dn\n" +
            "ds-vf\n" +
            "qq-zl\n" +
            "ll-ng\n" +
            "lx-fy\n" +
            "qz-qu\n" +
            "td-nh\n" +
            "kz-wm\n" +
            "ug-su\n" +
            "xb-ax\n" +
            "lj-zs\n" +
            "uw-xr\n" +
            "ca-il\n" +
            "db-yv\n" +
            "ni-nu\n" +
            "el-cm\n" +
            "ev-ph\n" +
            "zb-xu\n" +
            "ls-wx\n" +
            "ct-ee\n" +
            "dv-vv\n" +
            "ho-tm\n" +
            "wg-he\n" +
            "vg-ao\n" +
            "xp-ig\n" +
            "sb-tw\n" +
            "jw-dx\n" +
            "sx-tj\n" +
            "el-np\n" +
            "ks-kk\n" +
            "jm-sw\n" +
            "vx-hl\n" +
            "mt-sm\n" +
            "lj-nd\n" +
            "ae-uw\n" +
            "hz-nh\n" +
            "cc-no\n" +
            "ff-lj\n" +
            "yt-wx\n" +
            "ji-mv\n" +
            "yq-mc\n" +
            "qp-kd\n" +
            "pz-tm\n" +
            "yq-tj\n" +
            "gn-fi\n" +
            "nk-ga\n" +
            "sm-bv\n" +
            "gr-cl\n" +
            "uf-rq\n" +
            "ii-rt\n" +
            "be-jm\n" +
            "ld-ty\n" +
            "ol-py\n" +
            "dm-xn\n" +
            "zq-rq\n" +
            "ut-uc\n" +
            "lx-kn\n" +
            "cn-pf\n" +
            "pf-ab\n" +
            "zk-hv\n" +
            "qk-xb\n" +
            "ti-xy\n" +
            "tn-ra\n" +
            "be-ym\n" +
            "xd-dr\n" +
            "tn-ju\n" +
            "sm-ta\n" +
            "vi-xa\n" +
            "dd-eh\n" +
            "rz-gn\n" +
            "dp-xp\n" +
            "vj-fq\n" +
            "va-pr\n" +
            "sp-yi\n" +
            "eg-ei\n" +
            "ug-gs\n" +
            "fz-jg\n" +
            "nr-fv\n" +
            "ak-zn\n" +
            "vn-ai\n" +
            "bu-nb\n" +
            "gv-ex\n" +
            "ff-ea\n" +
            "mk-ku\n" +
            "so-ug\n" +
            "jn-nl\n" +
            "dc-pr\n" +
            "vv-fe\n" +
            "mo-tl\n" +
            "oa-yn\n" +
            "kd-in\n" +
            "tp-kx\n" +
            "ag-jt\n" +
            "rt-pd\n" +
            "ol-wl\n" +
            "ai-zn\n" +
            "kc-ju\n" +
            "jg-is\n" +
            "vy-fv\n" +
            "ha-mx\n" +
            "tb-rv\n" +
            "wg-ll\n" +
            "wn-vj\n" +
            "ii-ah\n" +
            "vk-ol\n" +
            "im-qc\n" +
            "lw-lr\n" +
            "yn-ki\n" +
            "yl-by\n" +
            "gm-fq\n" +
            "bl-at\n" +
            "mc-df\n" +
            "es-xn\n" +
            "nm-bs\n" +
            "yt-jz\n" +
            "hx-df\n" +
            "bj-wq\n" +
            "jm-tb\n" +
            "zv-qm\n" +
            "rt-lq\n" +
            "nl-kf\n" +
            "nc-gb\n" +
            "iu-cq\n" +
            "ej-jj\n" +
            "zc-rs\n" +
            "mx-bn\n" +
            "ax-hu\n" +
            "wc-it\n" +
            "cc-he\n" +
            "vf-cc\n" +
            "mq-gs\n" +
            "sd-fq\n" +
            "iu-dx\n" +
            "jc-yo\n" +
            "ih-ax\n" +
            "ed-hz\n" +
            "ra-ep\n" +
            "sz-pg\n" +
            "ot-ul\n" +
            "tp-mu\n" +
            "bf-ir\n" +
            "ez-xk\n" +
            "cv-su\n" +
            "kb-mz\n" +
            "kl-ng\n" +
            "ti-yz\n" +
            "jo-yn\n" +
            "pm-hc\n" +
            "ie-ot\n" +
            "uc-on\n" +
            "jf-ow\n" +
            "yr-uw\n" +
            "dh-kx\n" +
            "cf-go\n" +
            "mh-wl\n" +
            "vt-gd\n" +
            "tb-zf\n" +
            "om-zm\n" +
            "vv-nl\n" +
            "na-fs\n" +
            "vg-qk\n" +
            "nr-sx\n" +
            "ek-gj\n" +
            "xx-ks\n" +
            "vl-lr\n" +
            "oh-fd\n" +
            "il-ga\n" +
            "qn-om\n" +
            "vd-cj\n" +
            "gi-em\n" +
            "hf-bt\n" +
            "fi-em\n" +
            "xc-vw\n" +
            "ro-sb\n" +
            "ph-ov\n" +
            "jz-gp\n" +
            "qm-bf\n" +
            "hp-nd\n" +
            "in-zn\n" +
            "ee-bz\n" +
            "np-cm\n" +
            "nn-yx\n" +
            "ww-xq\n" +
            "nv-ym\n" +
            "so-gs\n" +
            "va-ry\n" +
            "ir-ur\n" +
            "ly-qo\n" +
            "ch-wi\n" +
            "on-jl\n" +
            "zg-jq\n" +
            "gy-pr\n" +
            "po-du\n" +
            "hq-lk\n" +
            "ow-ki\n" +
            "fw-ax\n" +
            "nc-du\n" +
            "mj-rj\n" +
            "kx-mu\n" +
            "jn-as\n" +
            "ek-nn\n" +
            "tb-ew\n" +
            "gv-lw\n" +
            "bm-kb\n" +
            "dd-hb\n" +
            "mj-dt\n" +
            "dw-ct\n" +
            "hp-rk\n" +
            "no-he\n" +
            "fs-dv\n" +
            "kk-vw\n" +
            "og-br\n" +
            "dl-pn\n" +
            "ov-ev\n" +
            "sz-gg\n" +
            "cs-go\n" +
            "xh-ju\n" +
            "nl-na\n" +
            "dp-mq\n" +
            "oo-ta\n" +
            "pr-ej\n" +
            "zw-xy\n" +
            "wz-lu\n" +
            "fv-qc\n" +
            "bx-qz\n" +
            "bu-ht\n" +
            "fz-qd\n" +
            "fq-si\n" +
            "kz-jw\n" +
            "re-hu\n" +
            "af-iw\n" +
            "wi-de\n" +
            "kn-ud\n" +
            "pw-ns\n" +
            "at-nr\n" +
            "tp-ax\n" +
            "ns-ax\n" +
            "bn-gb\n" +
            "tt-mr\n" +
            "nf-qp\n" +
            "eo-ds\n" +
            "qh-xt\n" +
            "cf-lk\n" +
            "zy-ei\n" +
            "ae-lt\n" +
            "lj-hv\n" +
            "ys-ub\n" +
            "et-qh\n" +
            "nz-xt\n" +
            "vr-ol\n" +
            "eg-rp\n" +
            "aw-zs\n" +
            "mz-jo\n" +
            "vy-oi\n" +
            "ze-xt\n" +
            "rk-aw\n" +
            "qx-ao\n" +
            "dy-vd\n" +
            "vc-an\n" +
            "bm-pe\n" +
            "rb-pt\n" +
            "dt-rj\n" +
            "sq-mp\n" +
            "yl-hg\n" +
            "mo-gj\n" +
            "gi-cr\n" +
            "ty-hz\n" +
            "hc-kc\n" +
            "ly-ru\n" +
            "um-dh\n" +
            "wx-cs\n" +
            "js-dn\n" +
            "vd-js\n" +
            "sk-xe\n" +
            "el-jp\n" +
            "al-gh\n" +
            "ws-jc\n" +
            "or-ni\n" +
            "bt-ep\n" +
            "jo-ki\n" +
            "xn-vb\n" +
            "yy-sy\n" +
            "zy-hg\n" +
            "um-ko\n" +
            "vs-lc\n" +
            "im-lu\n" +
            "ko-hx\n" +
            "dn-ri\n" +
            "py-wl\n" +
            "yy-an\n" +
            "qu-fh\n" +
            "bn-wx\n" +
            "st-gv\n" +
            "sh-ls\n" +
            "lr-ef\n" +
            "cl-xl\n" +
            "pc-wc\n" +
            "vn-in\n" +
            "dp-gj\n" +
            "cn-io\n" +
            "cm-hs\n" +
            "pg-ph\n" +
            "mq-sv\n" +
            "ou-nn\n" +
            "fn-yk\n" +
            "ne-ah\n" +
            "yg-oq\n" +
            "so-sv\n" +
            "mq-ug\n" +
            "sw-nv\n" +
            "pg-ov\n" +
            "qo-et\n" +
            "fe-kf\n" +
            "rz-sq\n" +
            "nd-vu\n" +
            "dq-we\n" +
            "gd-li\n" +
            "go-if\n" +
            "cr-lv\n" +
            "ii-pd\n" +
            "vt-my\n" +
            "sf-yq\n" +
            "pc-yg\n" +
            "gn-em\n" +
            "pe-oa\n" +
            "em-mp\n" +
            "qw-sw\n" +
            "hh-zi\n" +
            "so-mi\n" +
            "bs-ie\n" +
            "xc-cq\n" +
            "gl-oi\n" +
            "yz-jj\n" +
            "zj-tk\n" +
            "or-jx\n" +
            "vh-wv\n" +
            "xa-qn\n" +
            "al-lx\n" +
            "aw-nd\n" +
            "pa-oe\n" +
            "av-cc\n" +
            "hd-dn\n" +
            "dr-mg\n" +
            "dg-qp\n" +
            "vd-xg\n" +
            "ci-pr\n" +
            "mk-jx\n" +
            "ea-nd\n" +
            "tb-be\n" +
            "ew-ij\n" +
            "hw-sk\n" +
            "gu-ga\n" +
            "dl-bx\n" +
            "tt-qy\n" +
            "dy-bz\n" +
            "hf-ju\n" +
            "yi-iw\n" +
            "bw-ew\n" +
            "lt-po\n" +
            "kn-xp\n" +
            "io-ht\n" +
            "vh-de\n" +
            "xu-rr\n" +
            "yz-gy\n" +
            "yq-hx\n" +
            "rr-ig\n" +
            "iq-lm\n" +
            "fo-ob\n" +
            "lx-ez\n" +
            "it-yg\n" +
            "fo-kz\n" +
            "lr-fd\n" +
            "lj-pk\n" +
            "du-lt\n" +
            "zh-ro\n" +
            "gi-ox\n" +
            "om-mv\n" +
            "sv-su\n" +
            "vk-mh\n" +
            "vw-yi\n" +
            "wk-jf\n" +
            "kd-jc\n" +
            "zg-ch\n" +
            "bg-pw\n" +
            "zh-sb\n" +
            "qe-fx\n" +
            "fl-bz\n" +
            "ns-qx\n" +
            "hh-xd\n" +
            "wg-vf\n" +
            "at-oi\n" +
            "xq-io\n" +
            "jf-jo\n" +
            "vh-ch\n" +
            "tj-vy\n" +
            "vr-dd\n" +
            "sb-fp\n" +
            "qd-ja\n" +
            "rr-wl\n" +
            "kt-fo\n" +
            "pk-jq\n" +
            "hp-ea\n" +
            "uz-pn\n" +
            "io-pf\n" +
            "wx-mx\n" +
            "df-rc\n" +
            "ks-px\n" +
            "qh-ny\n" +
            "tw-fj\n" +
            "nv-hj\n" +
            "es-vo\n" +
            "xp-xe\n" +
            "gp-ha\n" +
            "lr-gv\n" +
            "kf-au\n" +
            "fi-rz\n" +
            "bx-pl\n" +
            "po-ni\n" +
            "js-cj\n" +
            "oa-jf\n" +
            "iw-xc\n" +
            "rs-pu\n" +
            "ju-ra\n" +
            "ak-hg\n" +
            "yx-bc\n" +
            "hc-ju\n" +
            "xa-gc\n" +
            "mo-dp\n" +
            "mr-xa\n" +
            "jq-wi\n" +
            "xy-ky\n" +
            "nq-rs\n" +
            "gl-vy\n" +
            "ny-zl\n" +
            "vk-zb\n" +
            "cl-ro\n" +
            "ib-ja\n" +
            "gj-xf\n" +
            "at-sx\n" +
            "tw-mj\n" +
            "ge-ep\n" +
            "oe-ek\n" +
            "by-in\n" +
            "fx-ff\n" +
            "kt-lh\n" +
            "to-nx\n" +
            "sh-mx\n" +
            "ka-ge\n" +
            "bz-xg\n" +
            "yx-zv\n" +
            "vu-ks\n" +
            "oa-wk\n" +
            "hu-ih\n" +
            "ne-zc\n" +
            "az-pc\n" +
            "ta-rb\n" +
            "zy-eg\n" +
            "uz-bx\n" +
            "hd-vd\n" +
            "cn-nb\n" +
            "vr-dg\n" +
            "rl-al\n" +
            "mr-fu\n" +
            "ie-vi\n" +
            "zc-ii\n" +
            "is-dh\n" +
            "jg-dh\n" +
            "vs-gu\n" +
            "fx-zs\n" +
            "ii-ql\n" +
            "zt-mv\n" +
            "wx-uj\n" +
            "lh-wm\n" +
            "ph-de\n" +
            "kb-ki\n" +
            "nf-ud\n" +
            "ud-ez\n" +
            "ul-nm\n" +
            "cu-ny\n" +
            "id-fw\n" +
            "nf-yo\n" +
            "ym-ck\n" +
            "xy-pn\n" +
            "it-nh\n" +
            "wn-si\n" +
            "xg-ee\n" +
            "jf-mz\n" +
            "iu-oo\n" +
            "ic-fq\n" +
            "mv-qn\n" +
            "fq-jl\n" +
            "hh-rb\n" +
            "ou-ey\n" +
            "hc-ge\n" +
            "ef-eb\n" +
            "qq-ob\n" +
            "ov-gg\n" +
            "rj-cl\n" +
            "st-fd\n" +
            "ff-hp\n" +
            "eb-ex\n" +
            "pl-zw\n" +
            "rk-wq\n" +
            "ib-qd\n" +
            "cn-kq\n" +
            "fx-rk\n" +
            "wn-ic\n" +
            "tw-xl\n" +
            "es-ho\n" +
            "ks-iq\n" +
            "vt-ji\n" +
            "ja-is\n" +
            "lm-vu\n" +
            "cn-ht\n" +
            "vb-pz\n" +
            "vt-qn\n" +
            "jq-le\n" +
            "eb-lr\n" +
            "eh-gn\n" +
            "ij-rl\n" +
            "lx-cw\n" +
            "dx-zl\n" +
            "bu-pf\n" +
            "rc-hl\n" +
            "no-ng\n" +
            "ev-zq\n" +
            "rt-ku\n" +
            "vk-qs\n" +
            "xq-da\n" +
            "vr-nf\n" +
            "pd-lq\n" +
            "ov-cb\n" +
            "gs-dp\n" +
            "oo-dr\n" +
            "by-eg\n" +
            "dm-ho\n" +
            "hj-bc\n" +
            "yi-xx\n" +
            "dt-fj\n" +
            "ee-vd\n" +
            "mo-so\n" +
            "oh-eb\n" +
            "uz-qw\n" +
            "mu-dh\n" +
            "hx-sn\n" +
            "fl-dw\n" +
            "kz-lb\n" +
            "dd-zj\n" +
            "ot-qy\n" +
            "ml-ga\n" +
            "pl-ur\n" +
            "ea-aw\n" +
            "is-qd\n" +
            "re-ha\n" +
            "jp-fa\n" +
            "df-oz\n" +
            "ei-ai\n" +
            "gl-lu\n" +
            "wk-ys\n" +
            "ax-vg\n" +
            "bu-kq\n" +
            "qq-kz\n" +
            "mf-bl\n" +
            "gk-mr\n" +
            "nu-gb\n" +
            "xr-or\n" +
            "ci-nw\n" +
            "up-ky\n" +
            "bw-ij\n" +
            "jo-pz\n" +
            "ka-ra\n" +
            "vs-ga\n" +
            "el-ma\n" +
            "ho-to\n" +
            "ug-ta\n" +
            "og-hs\n" +
            "pw-qx\n" +
            "jz-uj\n" +
            "vo-vf\n" +
            "kl-oj\n" +
            "fe-jn\n" +
            "ny-qo\n" +
            "bg-ax\n" +
            "sw-zf\n" +
            "nf-jc\n" +
            "py-ue\n" +
            "ig-zb\n" +
            "dr-hh\n" +
            "cj-xg\n" +
            "oh-vl\n" +
            "we-cs\n" +
            "rw-vh\n" +
            "gu-il\n" +
            "lt-nu\n" +
            "yq-jx\n" +
            "iu-mg\n" +
            "ys-bm\n" +
            "gr-ro\n" +
            "ko-is\n" +
            "uv-gi\n" +
            "rc-yq\n" +
            "wm-sr\n" +
            "lm-px\n" +
            "su-gj\n" +
            "wr-gx\n" +
            "ur-co\n" +
            "sh-wx\n" +
            "on-hh\n" +
            "at-im\n" +
            "aw-hp\n" +
            "ko-ja\n" +
            "eg-ak\n" +
            "cj-ie\n" +
            "ng-yb\n" +
            "rs-cv\n" +
            "wm-yh\n" +
            "lx-sk\n" +
            "my-qn\n" +
            "cv-ql\n" +
            "qc-vy\n" +
            "ww-da\n" +
            "lr-kx\n" +
            "ah-rs\n" +
            "bc-qm\n" +
            "qu-zw\n" +
            "qo-sg\n" +
            "xb-sz\n" +
            "bv-cq\n" +
            "dv-zp\n" +
            "zi-qs\n" +
            "hq-we\n" +
            "ph-sz\n" +
            "yg-ty\n" +
            "gg-wz\n" +
            "lu-qc\n" +
            "ku-mc\n" +
            "iq-kk\n" +
            "vd-bz\n" +
            "oq-or\n" +
            "jz-sj\n" +
            "bc-bf\n" +
            "wz-cb\n" +
            "ih-fw\n" +
            "sq-ox\n" +
            "cr-fi\n" +
            "sm-hh\n" +
            "xa-ul\n" +
            "lj-wq\n" +
            "hz-zz\n" +
            "jl-uc\n" +
            "xj-yz\n" +
            "fi-ox\n" +
            "ot-gc\n" +
            "bz-js\n" +
            "yd-wl\n" +
            "sx-gl\n" +
            "in-up\n" +
            "yr-id\n" +
            "zk-cs\n" +
            "zf-qw\n" +
            "vo-dm\n" +
            "mv-vt\n" +
            "by-ai\n" +
            "ol-yd\n" +
            "wn-jl\n" +
            "ut-si\n" +
            "sd-ic\n" +
            "or-uw\n" +
            "bn-ha\n" +
            "rs-pd\n" +
            "jj-jv\n" +
            "ll-eo\n" +
            "fw-ao\n" +
            "qk-lk\n" +
            "xk-al\n" +
            "eh-ox\n" +
            "zm-li\n" +
            "dy-xg\n" +
            "ls-ts\n" +
            "ov-wz\n" +
            "pa-bc\n" +
            "xi-vj\n" +
            "gp-wx\n" +
            "sz-zq\n" +
            "vo-gx\n" +
            "yd-vk\n" +
            "yg-td\n" +
            "aw-pk\n" +
            "yh-lh\n" +
            "ie-qy\n" +
            "ku-jx\n" +
            "ez-fy\n" +
            "pu-pd\n" +
            "ra-ow\n" +
            "fj-ui\n" +
            "vf-no\n" +
            "wg-oj\n" +
            "py-xu\n" +
            "td-az\n" +
            "oz-gv\n" +
            "pv-hs\n" +
            "td-wc\n" +
            "mu-ja\n" +
            "hd-ri\n" +
            "om-vb\n" +
            "hw-lx\n" +
            "pm-ep\n" +
            "zq-uf\n" +
            "sk-kn\n" +
            "rj-ui\n" +
            "vf-yb\n" +
            "zt-ag\n" +
            "oc-br\n" +
            "ey-pa\n" +
            "pu-wp\n" +
            "ef-lw\n" +
            "wo-sd\n" +
            "kd-mt\n" +
            "ct-js\n" +
            "in-ei\n" +
            "de-db\n" +
            "wr-nx\n" +
            "zp-du\n" +
            "oz-lr\n" +
            "fn-xx\n" +
            "zf-be\n" +
            "om-jt\n" +
            "to-vo\n" +
            "dc-yz\n" +
            "qq-sr\n" +
            "tn-hc\n" +
            "fe-na\n" +
            "kt-yh\n" +
            "tt-ie\n" +
            "ge-pm\n" +
            "qy-nm\n" +
            "vl-eb\n" +
            "mg-rb\n" +
            "rt-pu\n" +
            "to-xn\n" +
            "zw-dl\n" +
            "bf-yx\n" +
            "hg-rp\n" +
            "fd-ef\n" +
            "es-to\n" +
            "gn-lv\n" +
            "wv-yv\n" +
            "no-yb\n" +
            "bg-vg\n" +
            "ot-xa\n" +
            "gd-fh\n" +
            "zj-vr\n" +
            "ne-pd\n" +
            "cs-sa\n" +
            "wk-mz\n" +
            "cm-bl\n" +
            "dt-xl\n" +
            "wr-pz\n" +
            "kd-dd\n" +
            "nq-pu\n" +
            "rw-mj\n" +
            "xb-hu\n" +
            "on-si\n" +
            "io-vw\n" +
            "xb-vg\n" +
            "vu-xx\n" +
            "mg-ta\n" +
            "ox-gn\n" +
            "qj-sf\n" +
            "um-qd\n" +
            "eb-gv\n" +
            "eo-oj\n" +
            "qp-zj\n" +
            "ie-mr\n" +
            "yo-hb\n" +
            "cu-ze\n" +
            "tm-es\n" +
            "dd-nf\n" +
            "em-cr\n" +
            "cv-pd\n" +
            "is-um\n" +
            "xr-du\n" +
            "ib-kx\n" +
            "pg-gg\n" +
            "jf-pe\n" +
            "oq-lt\n" +
            "le-wv\n" +
            "is-sx\n" +
            "bn-ls\n" +
            "xl-mj\n" +
            "jt-li\n" +
            "fz-tp\n" +
            "ue-ol\n" +
            "uz-zw\n" +
            "bi-vk\n" +
            "xq-ab\n" +
            "uc-sd\n" +
            "jo-ow\n" +
            "vl-oz\n" +
            "fs-jn\n" +
            "lm-xx\n" +
            "rv-ra\n" +
            "yh-qq\n" +
            "xb-ih\n" +
            "ni-ii\n" +
            "lq-pu\n" +
            "wr-to\n" +
            "ep-tn\n" +
            "ek-zv\n" +
            "nw-jv\n" +
            "uc-wn\n" +
            "mp-vq\n" +
            "cb-gg\n" +
            "tl-so\n" +
            "dc-ti\n" +
            "gh-sk\n" +
            "lq-cf\n" +
            "oe-qm\n" +
            "ai-rp\n" +
            "qn-zm\n" +
            "va-he\n" +
            "fp-tw\n" +
            "ax-qk\n" +
            "py-rr\n" +
            "oq-du\n" +
            "iv-bn\n" +
            "ed-it\n" +
            "pr-ak\n" +
            "dg-zj\n" +
            "rc-vx\n" +
            "vn-ak\n" +
            "ho-wr\n" +
            "lt-xr\n" +
            "mf-sx\n" +
            "qh-ru\n" +
            "ed-zz\n" +
            "dw-dy\n" +
            "kk-yi\n" +
            "db-lt\n" +
            "yk-sv\n" +
            "sr-nm\n" +
            "oi-lu\n" +
            "eb-yr\n" +
            "rl-nv\n" +
            "gh-lx\n" +
            "cn-us\n" +
            "mu-jg\n" +
            "iu-xd\n" +
            "hd-dw\n" +
            "bg-xb\n" +
            "nk-ca\n" +
            "rk-qe\n" +
            "ir-qm\n" +
            "qe-bj\n" +
            "yh-kz\n" +
            "ji-gd\n" +
            "ig-bi\n" +
            "mj-fp\n" +
            "pf-us\n" +
            "an-ca\n" +
            "vl-id\n" +
            "wh-be\n" +
            "ls-iv\n" +
            "nu-du\n" +
            "bv-pt\n" +
            "kb-ys\n" +
            "bu-io\n" +
            "gq-vv\n" +
            "db-rh\n" +
            "zf-bw\n" +
            "de-zg\n" +
            "qm-yx\n" +
            "jr-ql\n" +
            "ls-jz\n" +
            "vo-ck\n" +
            "dx-yh\n" +
            "nd-bj\n" +
            "hd-xg\n" +
            "uf-gg\n" +
            "no-rj\n" +
            "jl-oe\n" +
            "aw-fx\n" +
            "gk-cn\n" +
            "vb-to\n" +
            "gn-vq\n" +
            "zv-hj\n" +
            "zj-mt\n" +
            "gd-lg\n" +
            "rl-ew\n" +
            "ji-hc\n" +
            "hp-wq\n" +
            "ed-nh\n" +
            "fs-fe\n" +
            "zy-zn\n" +
            "bu-cn\n" +
            "rh-zg\n" +
            "oi-qe\n" +
            "oi-mf\n" +
            "xf-sv\n" +
            "mi-ny\n" +
            "ct-dn\n" +
            "ux-hz\n" +
            "ue-es\n" +
            "xd-sm\n" +
            "gg-zq\n" +
            "sb-cl\n" +
            "mz-ys\n" +
            "al-kn\n" +
            "gj-mq\n" +
            "we-if\n" +
            "ce-fa\n" +
            "re-ax\n" +
            "wo-si\n" +
            "dq-go\n" +
            "wt-ma\n" +
            "ds-yb\n" +
            "ry-jj\n" +
            "vi-ul\n" +
            "qw-ij\n" +
            "mk-mc\n" +
            "im-bl\n" +
            "wo-xi\n" +
            "xr-ae\n" +
            "lh-qq\n" +
            "ph-uf\n" +
            "lj-fx\n" +
            "bt-lv\n" +
            "ww-io\n" +
            "lt-or\n" +
            "wk-bm\n" +
            "sp-zj\n" +
            "ot-nm\n" +
            "qe-wq\n" +
            "vn-zn\n" +
            "rq-wz\n" +
            "ko-mu\n" +
            "ny-ly\n" +
            "ru-ro\n" +
            "nx-es\n" +
            "xc-af\n" +
            "nw-va\n" +
            "ag-lg\n" +
            "kl-vf\n" +
            "ir-bc\n" +
            "xa-qy\n" +
            "gs-gx\n" +
            "jw-lb\n" +
            "bc-nn\n" +
            "wl-zb\n" +
            "so-fn\n" +
            "iq-af\n" +
            "vk-ig\n" +
            "cq-zi\n" +
            "pu-mb\n" +
            "mj-cl\n" +
            "rh-yv\n" +
            "ej-dc\n" +
            "oh-cc\n" +
            "oe-ou\n" +
            "ky-qu\n" +
            "zc-ql\n" +
            "pw-fw\n" +
            "vj-wo\n" +
            "iu-rb\n" +
            "ly-sg\n" +
            "ty-td\n" +
            "xi-on\n" +
            "vf-ul\n" +
            "xq-kq\n" +
            "pt-cq\n" +
            "ut-wo\n" +
            "tl-ug\n" +
            "gm-on\n" +
            "oi-nr\n" +
            "mz-yn\n" +
            "fn-dp\n" +
            "ze-qo\n" +
            "ho-nx\n" +
            "vc-lc\n" +
            "kn-fy\n" +
            "jp-pv\n" +
            "zt-li\n" +
            "rq-cb\n" +
            "qb-rq\n" +
            "sp-iq\n" +
            "hf-tm\n" +
            "ov-rq\n" +
            "mb-jg\n" +
            "be-sw\n" +
            "qu-bx\n" +
            "ed-wc\n" +
            "nx-fy\n" +
            "bx-ot\n" +
            "dl-ky\n" +
            "bx-xy\n" +
            "ol-bi\n" +
            "ji-my\n" +
            "hc-ka\n" +
            "st-oz\n" +
            "jf-tb\n" +
            "uf-pg\n" +
            "zn-ei\n" +
            "df-hl\n" +
            "ni-gb\n" +
            "ko-ib\n" +
            "ti-nw\n" +
            "ag-li\n" +
            "sy-ca\n" +
            "iv-sh\n" +
            "vw-lm\n" +
            "wi-yv\n" +
            "cu-qh\n" +
            "nc-zp\n" +
            "mq-so\n" +
            "nr-qc\n" +
            "sm-zi\n" +
            "ml-vs\n" +
            "zs-ea\n" +
            "ka-bt\n" +
            "ns-ih\n" +
            "bv-zi\n" +
            "fs-aj\n" +
            "fd-yr\n" +
            "xw-jn\n" +
            "fu-qy\n" +
            "ka-hf\n" +
            "mb-mu\n" +
            "nx-pz\n" +
            "aw-wq\n" +
            "pw-ih\n" +
            "vr-kd\n" +
            "gl-nr\n" +
            "ha-yt\n" +
            "yz-pr\n" +
            "it-ux\n" +
            "xn-ho\n" +
            "cu-xt\n" +
            "it-ty\n" +
            "jp-np\n" +
            "mh-ue\n" +
            "nh-ty\n" +
            "wv-wi\n" +
            "lx-xp\n" +
            "qc-oi\n" +
            "ao-xb\n" +
            "sm-dr\n" +
            "lk-sa\n" +
            "pu-ah\n" +
            "fh-zw\n" +
            "mp-rz\n" +
            "ml-sy\n" +
            "nl-aj\n" +
            "xi-si\n" +
            "yy-lc\n" +
            "rv-xh\n" +
            "vt-lg\n" +
            "oa-ki\n" +
            "rv-bt\n" +
            "jc-mt\n" +
            "ud-hw\n" +
            "sp-iw\n" +
            "xu-px\n" +
            "sq-lv\n" +
            "rw-rh\n" +
            "ej-va\n" +
            "vr-yo\n" +
            "gk-xq\n" +
            "kc-ka\n" +
            "oc-wt\n" +
            "yd-rr\n" +
            "ew-be\n" +
            "rb-xd\n" +
            "cw-ud\n" +
            "uj-ha\n" +
            "al-fy\n" +
            "av-ds\n" +
            "sq-eh\n" +
            "cr-eh\n" +
            "sd-vj\n" +
            "ww-cn\n" +
            "kk-iw\n" +
            "zy-yl\n" +
            "pn-zw\n" +
            "oe-ey\n" +
            "kl-av\n" +
            "ot-yu\n" +
            "po-or\n" +
            "ql-pu\n" +
            "xw-fe\n" +
            "tk-nf\n" +
            "pk-ea\n" +
            "lh-dx\n" +
            "fi-vq\n" +
            "ce-hs\n" +
            "fa-el\n" +
            "dl-pl\n" +
            "gi-fi\n" +
            "jf-bm\n" +
            "ru-sg\n" +
            "ty-zz\n" +
            "sy-vc\n" +
            "ex-fd\n" +
            "iw-iq\n" +
            "bl-tj\n" +
            "iu-bv\n" +
            "xj-pr\n" +
            "vy-nr\n" +
            "ii-jr\n" +
            "jc-qp\n" +
            "so-xf\n" +
            "rt-zc\n" +
            "ty-ib\n" +
            "sj-ov\n" +
            "wc-ty\n" +
            "wx-iv\n" +
            "ck-es\n" +
            "pk-nd\n" +
            "ng-av\n" +
            "ow-yn\n" +
            "tj-im\n" +
            "xx-sp\n" +
            "ab-gk\n" +
            "up-ak\n" +
            "gy-sg\n" +
            "tk-ws\n" +
            "cj-dw\n" +
            "uj-bn\n" +
            "ex-lw\n" +
            "lm-fp\n" +
            "ul-tt\n" +
            "hf-ep\n" +
            "mz-oa\n" +
            "qq-jw\n" +
            "ky-zw\n" +
            "dd-sx\n" +
            "mp-gi\n" +
            "bk-hq\n" +
            "mk-df\n" +
            "jo-ub\n" +
            "ku-el\n" +
            "yu-ul\n" +
            "ml-ca\n" +
            "ku-hl\n" +
            "dp-yk\n" +
            "px-xx\n" +
            "fn-su\n" +
            "xa-bs\n" +
            "lc-tk\n" +
            "dv-na\n" +
            "vs-nk\n" +
            "rl-ym\n" +
            "tj-qc\n" +
            "zl-lb\n" +
            "gk-us\n" +
            "eo-wg\n" +
            "jl-gm\n" +
            "ub-mz\n" +
            "lb-yh\n" +
            "zv-bf\n" +
            "js-ri\n" +
            "ox-em\n" +
            "vg-fw\n" +
            "hq-hv\n" +
            "om-vt\n" +
            "wh-ym\n" +
            "id-lw\n" +
            "jc-zj\n" +
            "mt-hb\n" +
            "gg-wc\n" +
            "ah-rt\n" +
            "hf-xh\n" +
            "qk-fw\n" +
            "iu-dr\n" +
            "yh-fo\n" +
            "ll-vf\n" +
            "pz-es\n" +
            "mi-ze\n" +
            "sq-iw\n" +
            "ww-kq\n" +
            "hw-fy\n" +
            "ib-tp\n" +
            "mr-vi\n" +
            "fd-jq\n" +
            "ib-mu\n" +
            "ka-pm\n" +
            "rv-tn\n" +
            "oc-hs\n" +
            "xf-su\n" +
            "em-uv\n" +
            "hd-js\n" +
            "fx-bj\n" +
            "up-ai\n" +
            "vu-px\n" +
            "zl-wm\n" +
            "gr-sb\n" +
            "ig-mh\n" +
            "js-ak\n" +
            "us-io\n" +
            "cl-fj\n" +
            "gx-dm\n" +
            "zt-ji\n" +
            "sf-vx\n" +
            "gu-vc\n" +
            "xw-dv\n" +
            "oc-ce\n" +
            "kd-nf\n" +
            "et-nz\n" +
            "ou-ek\n" +
            "mr-nm\n" +
            "pm-tn\n" +
            "mp-uv\n" +
            "qs-bi\n" +
            "uz-ur\n" +
            "dg-ws\n" +
            "hf-ge\n" +
            "ut-xi\n" +
            "lb-ob\n" +
            "ih-qk\n" +
            "fw-ns\n" +
            "cf-we\n" +
            "qh-ze\n" +
            "hf-tn\n" +
            "ko-tp\n" +
            "el-pv\n" +
            "qb-pg\n" +
            "ez-kn\n" +
            "vj-xk\n" +
            "hw-xp\n" +
            "dx-kt\n" +
            "ee-cj\n" +
            "iu-sm\n" +
            "vk-py\n" +
            "xh-ep\n" +
            "yr-vl\n" +
            "ug-sv\n" +
            "ou-bc\n" +
            "he-av\n" +
            "wo-fq\n" +
            "wi-wp\n" +
            "mt-yo\n" +
            "ho-dl\n" +
            "sw-eo\n" +
            "vd-dw\n" +
            "nz-ly\n" +
            "ta-pt\n" +
            "so-gj\n" +
            "cf-jb\n" +
            "nn-zv\n" +
            "bj-rk\n" +
            "ky-bx\n" +
            "vj-gm\n" +
            "lb-qq\n" +
            "ag-om\n" +
            "rk-zs\n" +
            "jb-go\n" +
            "hq-cf\n" +
            "wm-fo\n" +
            "aj-xw\n" +
            "ca-ga\n" +
            "xh-bt\n" +
            "wo-ic\n" +
            "qn-zt\n" +
            "vb-dm\n" +
            "cc-ng\n" +
            "ue-vk\n" +
            "dk-et\n" +
            "hg-zn\n" +
            "xt-mi\n" +
            "py-mh\n" +
            "nc-nu\n" +
            "nc-or\n" +
            "ao-pw\n" +
            "ah-jr\n" +
            "sn-hl\n" +
            "lv-rz\n" +
            "ou-pa\n" +
            "qj-hx\n" +
            "xv-ga\n" +
            "gl-wo\n" +
            "vg-re\n" +
            "ks-lx\n" +
            "sm-pt\n" +
            "fd-gv\n" +
            "hd-pn\n" +
            "ag-qn\n" +
            "au-na\n" +
            "vj-si\n" +
            "nq-pd\n" +
            "qq-fo\n" +
            "wh-ij\n" +
            "sv-yd\n" +
            "sb-xl\n" +
            "to-gx\n" +
            "vd-ct\n" +
            "ee-js\n" +
            "yy-nk\n" +
            "bj-zs\n" +
            "cf-if\n" +
            "wt-cm\n" +
            "em-sq\n" +
            "lm-af\n" +
            "ig-qs\n" +
            "ze-ly\n" +
            "eb-fd\n" +
            "uj-ea\n" +
            "tk-qp\n" +
            "ed-pc\n" +
            "yl-ei\n" +
            "jr-rs\n" +
            "rs-ii\n" +
            "zb-py\n" +
            "vs-sy\n" +
            "wo-uc\n" +
            "yr-st\n" +
            "xt-ly\n" +
            "ug-fn\n" +
            "ld-ux\n" +
            "pf-ht\n" +
            "rw-jq\n" +
            "vq-uv\n" +
            "cr-ox\n" +
            "da-io\n" +
            "fe-aj\n" +
            "sr-kz\n" +
            "ag-gd\n" +
            "zw-co\n" +
            "uv-ox\n" +
            "mf-nr\n" +
            "rj-sb\n" +
            "we-go\n" +
            "gr-rj\n" +
            "rl-tb\n" +
            "wv-db\n" +
            "pn-qz\n" +
            "ky-pn\n" +
            "ew-ym\n" +
            "mg-wz\n" +
            "mi-ly\n" +
            "mc-sf\n" +
            "rr-ol\n" +
            "qx-ih\n" +
            "ql-lq\n" +
            "nk-vc\n" +
            "bl-sx\n" +
            "pa-ek\n" +
            "to-fi\n" +
            "xn-nx\n" +
            "rl-sw\n" +
            "pe-ow\n" +
            "cc-ll\n" +
            "vi-nm\n" +
            "uc-vj\n" +
            "xy-uz\n" +
            "kb-oa\n" +
            "ry-gy\n" +
            "qu-co\n" +
            "oc-fa\n" +
            "hw-al\n" +
            "ev-kr\n" +
            "il-vs\n" +
            "cw-sk\n" +
            "ds-ll\n" +
            "xe-ud\n" +
            "pw-qk\n" +
            "vs-an\n" +
            "nc-uw\n" +
            "wv-wp\n" +
            "rw-le\n" +
            "wp-le\n" +
            "ws-qp\n" +
            "kl-wg\n" +
            "bz-dw\n" +
            "xc-ks\n" +
            "af-kk\n" +
            "yu-bs\n" +
            "jj-xj\n" +
            "aj-dv\n" +
            "jq-wp\n" +
            "da-us\n" +
            "pn-bx\n" +
            "ze-nz\n" +
            "cv-rt\n" +
            "ov-zq\n" +
            "vn-dt\n" +
            "bf-oj\n" +
            "aw-pc\n" +
            "ev-uf\n" +
            "dk-ly\n" +
            "gk-kq\n" +
            "vc-ml\n" +
            "fw-re\n" +
            "sz-wz\n" +
            "bv-dr\n" +
            "xf-ug\n" +
            "vu-af\n" +
            "bf-pa\n" +
            "wr-zv\n" +
            "xt-qo\n" +
            "wr-vo\n" +
            "ei-by\n" +
            "qx-bg\n" +
            "iu-hh\n" +
            "vs-yy\n" +
            "uc-xi\n" +
            "ky-qz\n" +
            "hv-sa\n" +
            "yv-vh\n" +
            "zw-wv\n" +
            "kz-ox\n" +
            "ff-rk\n" +
            "vy-lu\n" +
            "vy-bl\n" +
            "jv-ci\n" +
            "qb-gg\n" +
            "xu-bi\n" +
            "jw-wm\n" +
            "xx-iw\n" +
            "hf-kc\n" +
            "kx-ja\n" +
            "dg-tk\n" +
            "nk-an\n" +
            "zz-td\n" +
            "wm-qq\n" +
            "ko-mb\n" +
            "ud-sk\n" +
            "qm-ey\n" +
            "mi-ru\n" +
            "ku-hx\n" +
            "vi-qy\n" +
            "ds-cc\n" +
            "yu-mr\n" +
            "fh-xy\n" +
            "dv-au\n" +
            "jj-pr\n" +
            "cr-uv\n" +
            "xk-hw\n" +
            "nh-wc\n" +
            "jw-kt\n" +
            "oz-oh\n" +
            "qc-bl\n" +
            "bs-vi\n" +
            "wn-gm\n" +
            "kx-mb\n" +
            "oh-gv\n" +
            "fi-mp\n" +
            "dy-js\n" +
            "ob-kz\n" +
            "db-wp\n" +
            "tp-um\n" +
            "at-mf\n" +
            "ly-cu\n" +
            "fv-mf\n" +
            "ku-sn\n" +
            "jv-yz\n" +
            "bz-cj\n" +
            "ys-jo\n" +
            "ml-nk\n" +
            "qd-ea\n" +
            "sd-xi\n" +
            "fj-rj\n" +
            "ga-vc\n" +
            "ij-jm\n" +
            "ie-gc\n" +
            "ae-po\n" +
            "td-ux\n" +
            "ic-xi\n" +
            "hj-pa\n" +
            "wg-no\n" +
            "zs-qe\n" +
            "cc-yb\n" +
            "pn-co\n" +
            "xd-mg\n" +
            "bw-da\n" +
            "ww-ab\n" +
            "vg-ns";
    HashMap<String, Computer> computers;

    public void read() {
        computers = new HashMap<>();
        String[] lines = input.split("\n");
        for (String line : lines) {
            String[] pcs = line.split("-");
            computers.putIfAbsent(pcs[0], new Computer(pcs[0]));
            computers.putIfAbsent(pcs[1], new Computer(pcs[1]));
            computers.get(pcs[0]).conections.add(computers.get(pcs[1]));
            computers.get(pcs[1]).conections.add(computers.get(pcs[0]));
        }
    }

    public void part1() {
        read();
//        ArrayList<Result> results = new ArrayList<>();
//        for (Computer comp : computers.values()) {
//            if (comp.name.contains("t")) {
//                results.add(traverse(comp));
//            }
//        }
        ArrayList<Tri> results = new ArrayList<>();
        for (Computer comp : computers.values()) {
            if (comp.name.startsWith("t")) {
                results.addAll(find3(comp));
            }
        }
        HashMap<String, Tri> filtered = new HashMap<>();
        for (Tri result : results) {
            filtered.putIfAbsent(result.geyKey(), result);
        }
        for (Tri result : filtered.values()) {
            System.out.println(result);
        }
    }

    public Result traverse(Computer root) {
        Stack<Computer> stack = new Stack<>();
        stack.add(root);
        Result result = new Result(0, false);
        while (!stack.isEmpty()) {
            Computer computer = stack.pop();
            if (!computer.visited) {
                result.count++;
                computer.visited = true;
                if (computer.name.startsWith("t")) {
                    result.nameStartsWithT = true;
                }
                result.computers.add(computer);
                for (Computer conection : computer.conections) {
                    stack.push(conection);
                }
            }
        }
        return result;
    }

    public Collection<Tri> find3(Computer root) {
        ArrayList<Tri> result = new ArrayList<>();
        for (Computer conection : root.conections) {
            for (Computer computer : root.conections) {
                if (conection.equals(computer)) {
                    continue;
                }
                if (conection.conections.contains(computer)) {
                    result.add(new Tri(root, conection, computer));
                }
            }
        }
        return result;
    }

    public void part2() {
    }
}
